x-airflow-common: &airflow-common
  build:
    context: ../airflow
    dockerfile: Dockerfile
  user: "${AIRFLOW_UID:-50000}:0"
  restart: unless-stopped
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY:-}
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__PARALLELISM: ${AIRFLOW_PARALLELISM:-16}
    AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_DB_USER:-airflow}:${AIRFLOW_DB_PASSWORD:-airflow_password}@airflow-postgres/${AIRFLOW_DB_NAME:-airflow}"
    AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://${AIRFLOW_DB_USER:-airflow}:${AIRFLOW_DB_PASSWORD:-airflow_password}@airflow-postgres/${AIRFLOW_DB_NAME:-airflow}"
    AIRFLOW__CELERY__BROKER_URL: "redis://airflow-redis:6379/0"
    AVIASALES_TOKEN: ${AVIASALES_TOKEN:-}
    MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-}
    AIRFLOW_CONN_MONGO_DEFAULT: '{"conn_type":"mongo","host":"mongodb","port":27017,"login":"${MONGO_INITDB_ROOT_USERNAME}","password":"${MONGO_INITDB_ROOT_PASSWORD}","schema":"${MONGO_INITDB_DATABASE}","extra":{"authsource":"admin"}}'
    AIRFLOW_CONN_POSTGRES_DEFAULT: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}"
  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/logs:/opt/airflow/logs
    - ../airflow/plugins:/opt/airflow/plugins
  depends_on:
    airflow-postgres:
      condition: service_healthy
    airflow-redis:
      condition: service_healthy
  networks:
    - core

services:
  airflow-postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER:?required}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD:?required}
      POSTGRES_DB: ${AIRFLOW_DB_NAME:-airflow}
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AIRFLOW_DB_USER} -d ${AIRFLOW_DB_NAME:-airflow}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - core

  airflow-redis:
    image: redis:7
    restart: unless-stopped
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    ports:
      - "${AIRFLOW_REDIS_PORT:-6380}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - core

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username ${AIRFLOW_WWW_USER_USERNAME} --password ${AIRFLOW_WWW_USER_PASSWORD} --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: "no"
    depends_on:
      airflow-postgres:
        condition: service_healthy
      airflow-redis:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "${AIRFLOW_WEBSERVER_PORT:-8080}:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-worker:
    <<: *airflow-common
    command: celery worker

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer

volumes:
  airflow_postgres_data:

