services:
  backend_app:
    build: null
    image: ${REGISTRY:-ghcr.io/anntish/md_ticket_project}/backend_app:${TAG:-latest}
    command:
      - uvicorn
      - main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
    volumes: []

  airflow-init:
    build: null
    image: ${REGISTRY:-ghcr.io/anntish/md_ticket_project}/airflow:${TAG:-latest}
    volumes: []

  airflow-webserver:
    build: null
    image: ${REGISTRY:-ghcr.io/anntish/md_ticket_project}/airflow:${TAG:-latest}
    volumes: []

  airflow-scheduler:
    build: null
    image: ${REGISTRY:-ghcr.io/anntish/md_ticket_project}/airflow:${TAG:-latest}
    volumes: []

  airflow-worker:
    build: null
    image: ${REGISTRY:-ghcr.io/anntish/md_ticket_project}/airflow:${TAG:-latest}
    volumes: []

  airflow-triggerer:
    build: null
    image: ${REGISTRY:-ghcr.io/anntish/md_ticket_project}/airflow:${TAG:-latest}
    volumes: []

